POST http://localhost:3001/api/persons
Content-Type: application/json

{
	"name": "Mary Poppendieck",
	"number": "39-23-6423100"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
	"number": "123-456-7890"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
	"name": "Foo Bars"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
	"somethingElse": "foo bar"
}